# App Info
ios_app_id                                : 1480997301                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://itunes.apple.com/app/id1480997301                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://itunes.apple.com/app/id1480997301                                       # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bandze                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : App from Dutch trainer and lifestyle coach Radmilo Soda. Focussing on the improvement of the physical aspects using fitness bands.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Soda Bodyfit BV                                
your_link                                 : https://www.sodabodyfit.nl/            
your_city                                 : Amsterdam                                
email_address                             : info@sodabodyfit.nl
facebook_username                         : sodabodyfit                                       
instagram_username                        : radmilosoda
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Workout Categories
    description                           : Choose from different Workout Categories
    fontawesome_icon_name                 : running
    
  - title                                 : Explore our list of exercises
    description                           : Choose your favorites
    fontawesome_icon_name                 : heart

  - title                                 : Create your own Workouts
    description                           : Create your own Workouts from our list of exercises.
    fontawesome_icon_name                 : dumbbell

  - title                                 : Timer
    description                           : Use our in-app timer to train.
    fontawesome_icon_name                 : clock

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#214857"
cover_overlay_transparency                : 1

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "E6E6E6"

link_color                                : "#FFCC01"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#214857"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#214857"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
